---
title: "Data Import"
output: github_document
---


```{r setup}
library(tidyverse)
library(readxl)
 library(haven)
```

Import our first dataset

```{r}
litters_df = 
  read_csv(file = "./data/FAS_litters.csv")


litters_df = janitor::clean_names(litters_df)
```


```{r}
pups_df =
  read.csv("data/FAS_pups.csv", skip = 3) 
```

```{r}
pups_df

pups_df = janitor::clean_names(pups_df)
```

```{r}

litters_df
pups_df
```


```{r}
head(litters_df, 20)
tail(pups_df, 5)

```

```{r}

skimr::skim(pups_df)
```



## Options to read.csv

check out ?read_csv() more information

## Other Fle formats
REad in excel file

```{r}

mlb_df = read_excel("./data/mlb11.xlsx")
```

```{r}
mlb_df
```

Read in a SAS file

```{r}
pulse_df = read_sas("./data/public_pulse_data.sas7bdat")
pulse_df
```

## Comparison with Base R
what about read.csv?
ALWAYS use read_csv

```{r}
litters_base = read.csv("data/FAS_litters.csv")
litters_reader = read_csv("data/FAS_litters.csv")

litters_base
litters_reader
```

## Exporting Data
export mlb sub-table
```{r}
write_csv(mlb_df, "./data/mbl_subtable.csv")

```

