---
title: "Data Manipulation"
output: github_document
---


```{r setup}
library(tidyverse)
```

## Loa FAS Litters Data
```{r}
litters_df = read_csv("./data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df )

litters_df
```


## select

Choose some columns and not others
```{r}
select(litters_df, group, litter_number)

select(litters_df, group, gd0_weight:gd_of_birth)
```


```{r}
select(litters_df,-litter_number)
```


Renaming columns ...

```{r}
select(litters_df, GROUP = group, LITTer_NUmBer = litter_number)
```

Select helpers
```{r}
select(litters_df, starts_with("gd"))
```

```{r}
select(litters_df, litter_number, everything())
```


```{r}
relocate(litters_df, litter_number)
```

## filter


```{r}
filter(litters_df, gd0_weight < 22 )
```

```{r}
filter(litters_df, gd_of_birth == 20)
```

```{r}
filter(litters_df, !(gd_of_birth == 20))
```

```{r}
filter(litters_df, gd0_weight >= 22, gd_of_birth == 20)
```

```{r}
filter(litters_df, group == "Mod8")
```

```{r}
filter(litters_df, group %in% c("Con7", "Mod8"))
```

## mutate
```{r}
mutate(
  litters_df, 
  gd18_weight = as.numeric(gd18_weight),
  gd0_weight  = as.numeric(gd0_weight),
  wt_gain     = gd18_weight - gd0_weight
)
```

## 'arrange'
```{r}
arrange(litters_df, pups_born_alive)
```


## %>%
USE PIPE OPERATOR

```{r}
read_csv("./data/FAS_litters.csv") %>%
  janitor::clean_names() %>%
  select(-pups_survive)
mutate(wt_gain = gd18_weight - gd0_weight) %>%
  drop_na(gd0_weight)
```


